### ISSUE TITLE
gencumulativesky not found

### ISSUE THREAD

**Issue by tristanfabregas** [NREL/bifacial_radiance#261]
Dear all,

I have an error when I run the first example: **_1 - Introductory Example - Fixed Tilt simple setup.ipynb_**
"gencumulativesky" is not an internal or external command.
Same issue appears with "rtrace" which is linked to "Linescan in process: bifacial_example_Front
message.

I'm running Anaconda on W10, I've previously installed Radiance at the root of C:\, copied and pasted all other executables, changed paths..

No sure it's a bug, so if you have any idea of what I've done wrong it'll be very appreciated.

Regards,

**Comment by cdeline** [comment]
Hi Tristan, it sounds like your `Radiance\bin\` folder is not on your windows PATH.  If you open the  'environment variables' tab in Windows settings, you need to add the folder where all those executables are located.  Here's what mine looks like.  The order shouldn't matter. It may require a computer restart to take effect.  

![image](https://user-images.githubusercontent.com/23244088/83301350-b91c9780-a1b6-11ea-8c9b-c8244c95ee1c.png)

**Comment by tristanfabregas** [comment]
Thank you very much, the problem was solved by our IT guy who has installed radiance with admin privileges.
It works now.

Regards,
Tristan

**Comment by mulla1993** [comment]
Hello,

I am facing the same problem. I made sure that Radiance is under my path and I am using my private PC (Downloaded as administrator) and still getting the message: < 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.> Would you please advise.

BR,
Mohd

**Comment by tristanfabregas** [comment]
Hello, not sure if that solve the problem, but last time I've uninstalled and reinstalled Anaconda with right click and "launch as administrator" and the path was found.

Hope this helps
Tristan

**Comment by mulla1993** [comment]
Hello,

Doing the following solved it to me:
1- reinstalled Anaconda and Radiance as administrator
2- manually inserted the Anaconda and Radiance to both the User variable path and the system variable path.

Thanks! 
BR,
Mohd
