### ISSUE TITLE
Problem with solar altitude / timezone

### ISSUE THREAD

**Issue by dvalencia00** [NREL/bifacial_radiance#85]
When using the attached weatherfile, I get errors with the sun altitude. If the timezone is changed to 0 errors disapear, but there may be two problems: 1) this is not truth (because Spain timezone is +1); 2) I am not sure if this may affect the tracker angle or other calculations somehow.
I let you know that I have download the file from [PVGis ](http://re.jrc.ec.europa.eu/pvg_tools/en/tools.html)
I have checked some sunrise and sunset times [here ](https://www.timeanddate.com/sun/spain/murcia?month=8&year=2019)and they seems fine. Note that Spain increase 1 hour in spring-summer.
PS Attached file is .txt because is not possible upload .epw. Please change it before use it.
[Murcia_tmy_era_37.992_-1.131_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3058520/Murcia_tmy_era_37.992_-1.131_2007_2016.txt)

**Comment by shirubana** [comment]
Hello Daniel,

Couple questions to track this issue ~ Which version are you using?  Also which kind of errors are you getting? If you could paste a screenshot and identify one of the timestamps that is crashing that be ideal, or if you have an excel where you are tracking the sun position differences.

I know our current master version has some kinds on that and we improved on it on our latest development version. Mostly because sunrise and sunset hours, if the sun rises at let's say 7:40 am, the timestamp for 8 AM will have DNI and DHI values, but since the timestamp from 8 AM reffers to the hour of 7 to 8 the sunposition gets calculated at 7:30 AM , which for this case the sun would be below horizon. I'll try running the Murcia epw on my computer on the latest version see if it struggles too.

Also, it is my understanding EPWs do not consider daylight savings. I'm not sure if PVLib (which is what we are using to get sunposition) I'll investigate that.  I've done some comparisons with SPA before and didn't notice anything odd though ~ https://midcdmz.nrel.gov/solpos/spa.html

**Comment by dvalencia00** [comment]
Hi Silvana. I am using 0.2.4, but I got the same errors with 0.2.3. Attached is a txt with the text of the errors.
I confirm you that the Murcia EPW file timestamp is according to our winter time (even spring-summer data). I have not seen errors differences among seasons, so I guess this is not the problem. 
I have tested someEPW files from European cities and errors are just for some of them (Murcia, Madrid, Coruña, Bordeaux and Paris) while others do not show them (Brussels, Lisbon). Attached you have the weather files.

[Lisbon_tmy_era_38.708_-9.137_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3072110/Lisbon_tmy_era_38.708_-9.137_2007_2016.txt)
[Madrid_tmy_era_40.417_-3.704_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3072111/Madrid_tmy_era_40.417_-3.704_2007_2016.txt)
[Brussels_tmy_era_50.847_4.352_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3072112/Brussels_tmy_era_50.847_4.352_2007_2016.txt)
[Coruna_tmy_era_43.057_-8.53_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3072113/Coruna_tmy_era_43.057_-8.53_2007_2016.txt)
[Paris_tmy_era_48.853_2.364_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3072114/Paris_tmy_era_48.853_2.364_2007_2016.txt)
[Bordeaux_tmy_era_44.841_-0.58_2007_2016.txt](https://github.com/NREL/bifacial_radiance/files/3072115/Bordeaux_tmy_era_44.841_-0.58_2007_2016.txt)

[Errors with Murcia EPW.txt](https://github.com/NREL/bifacial_radiance/files/3071958/Errors.with.Murcia.EPW.txt)

**Comment by shirubana** [comment]
Hi Daniel,

Can you be more specific with the error you are getting? Is it for gendaylit - hour by hour procedure?  are you following the tracker option? Which day / hour in specific is crashing if you can give me an example for Murcia?

As I mentioned, we have updated the development version to avoid times when then sun is below the horizon., which was causing us to crash on the hour-by-hour analysis. IF this is the same bug you are encountering then I would suggest you use the development version ~ the whole process with the sun position from gendaylit to tracker changed quite a bit so I don't think it'll get bug-fixed in v. 0.2.4. 
![image](https://user-images.githubusercontent.com/22824806/56147597-d4522680-5f65-11e9-805b-a1bdb5e9a364.png)

**Comment by shirubana** [comment]
As a follow up.

I ran a couple tests with the Murcia EPW:
1) Gendaylit for single axis tracking. Ran correctly days FEb. 16 to March 2.
2) Gencumsky for tracking the whole year.
2) Gencumsky for fixed axis tracking the whole year.

Two and 3 ran correctly but gencumsky does return some errors for when sun is below horizon (it still continues) . This is the command that prints the error:
![image](https://user-images.githubusercontent.com/22824806/56150215-9eb03c00-5f6b-11e9-97db-7062bb831f45.png)
And this is the example of the error message.
![image](https://user-images.githubusercontent.com/22824806/56150349-f353b700-5f6b-11e9-992a-a3939b2ace0a.png)

It is deciding the sun is below the horizon for 247 hours of the year, but it is considering 4154 hours to create the sky.  This 247 hours represent 15245 W/m2 total of diffuse light not considered, distributed in the following way:
![image](https://user-images.githubusercontent.com/22824806/56152117-141e0b80-5f70-11e9-9b91-836e4c39b4de.png)

I don't think this represents a big change if we were to fix the executable for gencumsky (which was not developed by us) in terms of improving the simulation.

Anyways I'm not sure if any of these cases covers what you were seeing. I just uploaded a journal on the XandY version for all of these cases I tested above. I can't explore anything else on this issue until you tell me more exactly how to reproduce it, or if this and hte previuos exaplanations make sense and you'd rather just use our new procedure. I'll await your answer :)

**Comment by dvalencia00** [comment]
Hi Silvana. 
I confirm you that the errors you get are the ones I am talking about and I attached in a txt file in a previous comment (Errors with Murcia EPW.txt). I think you have not seen it :-). Sorry because I didnt said that my problem was using gencumsky.

In my case the error comes simulating with gencumsky and tracking but, from your analysis, it seems that the problem comes from gencumsky (it doesnt matter other parameters of the simulation).

I am not sure about what you mean with "use our new procedure". If the problem is from gencumsky, we can just assume that an small part of the radiation is not considered unless the algorithms in gencumsky are changed. Right? 

If you need something else, please let me know. Thanks a lot for your effort and anlysis of the problem.

**Comment by shirubana** [comment]
Ah! Excellent, thanks for sending the errors. And yes, it is an error in gencumsky/pvlib combo.

We have addressed this in the new version we are developing.  I don't know how fast it will get transferred to a formal Release version (we are shooting for before May 10th~ release).  I just ran Murcia epw in our hpc for the whole year and this new branch works well. What it does is it sets the sun's zenith angle to 89 for those times where there is DHI value before the sunrise hour, so the trackers position ends up being 0 degree tilt for those. It is a minimum contribution but at least now it doesn't crash! :)

If you need to run something before then, the X and Y branch is in stable conditions to be used right now so download it and try it before we continue doing additions to it. The journals have been documented for the procedural changes too (we simplified a ton of things). Let me know if I can help with anything else, I'm marking this as closed now!

**Comment by costeladebarata** [comment]
Hi guys,

I'm getting the same error, reading the thread I thought that by updating bifacial_radiance I would be fine but I'm still getting the error message.

Any solution to this problem? When comparing to PVsyst my front and rear irradiation are far off, and when I compare the solar altitude calculated by PVsyst and Radiance (the altitude that is shown in the error message) they are very different.

I've noticed it's a random issue, or better, it only happens at certain latitudes.
Anyone experiencing the same?

**Comment by shirubana** [comment]
Hola,

This thread is kinda old, and I think as we last communicated the sun position calculation for sunrise got fixed, I don't think you should encounter as many occurences of the sun being up and the software ignoring it as before. However , see below:

We were following SAM's sun position calculation, that for 1 hour intervals if the entry reads 11 AM, it calculates the sun position at 10:30 AM. Since May of this year, SAM switched to follow PVSyst, which does 11 AM -- sun position at 11:30 AM. We have thread open to add the option to select if you want a delta before or after the hour (or none) for the next release. This might be the differences you are seeing. 

https://github.com/NREL/bifacial_radiance/issues/211

If it's another thing, can you document you're error again with the newer version so we can fix it? Thank you

**Comment by costeladebarata** [comment]
Well, I'm not 100% sure it is the same problem, I'll try to explain it better.

The first thing to say is that I have ran many simulations successfully, benchmarking GII and GIIrear against PVsyst and found similar numbers. I'm saying this to rule out user errors operating Bifacial Radiance.

Now, when running my script (I'm using GenCumSky) I noticed many lines with the message "Error!  Solar altitude is -7 < -6 degrees and Idh = 129 > 10 W/m^2 on day 8 !Ibn is 0.  Attempting to continue!", for different solar altitudes.
Then, when I computed annual values I noticed GII and GIIrear are far below what I find in PVsyst, like 30% lower, which makes me think the code is leaving many timestamps behind because it considers to be "night" (negative solar altitude).

Is it the same issue? If you think it is I'm hapy to post under 0.3.4

Also, I tried following #211 but haven't managed to find any solution to this problem.

**Comment by shirubana** [comment]
What do you mean Gfront and Grear are 30% below PVSyst? Are you summing all your values for the year, or what is it that you are doing? Even if it missed all the sunrise hours of the year, those hours have very little content of irradiance and would not affect in such a manner the results. 

#211 has been solved in one of the latest commits to bifacialvf development branch around the time I created that issue, I just have to copy the code to the  function and push it to development on bifacial_radiance. Maybe I'll speed that up. 

Still, that is not what is giving you the discrepancy on results. In general, bifacial radiance also gives higher irradiance values of Grear than PVSyst. Can yo describe what scene parameters are you trying to do? Or maybe share one of your result csv files?

**Comment by costeladebarata** [comment]
I am summing the cumulative annual values at each tracker position (from irr_1axis_XX.csv, averaging across the module). I agree that it shouldn't have that much impact but it's not what I'm seeing.

Scena is a 1UP tracker, torque tube with 0.12m metal_grey, module dimensions 2.008x1.002, pitch 6.1m, hub height 1.4m.
lat 19.7 long -98.7
Am I forgetting something?

I understand BF Radiance will give higher irradiance for Grear (I'm fine with that), but the GII is 15% less than PVsyst and that's what I don't understand (sorry, bad math previously, 15% is correct).

I added one of the csv results, hope that's what you meant.
Thanks for the help!

**Comment by costeladebarata** [comment]
Sorry, didn't realize it doesn't support .csv or .rar

[irr_1axis_0.0.txt](https://github.com/NREL/bifacial_radiance/files/4003676/irr_1axis_0.0.txt)

**Comment by costeladebarata** [comment]
I ran a simulation using "GetEPW" at the project coordinates and had the same error message, I guess that rules out any problem with the .epw file.

I made some comparisons between the solar altitude in the error messages and PVsyst values for solar altitude (plus another source for solar altitude) and I think when the .epw says 18:00 (which should be irradiation between 17-18) the program is calculating the altitude for 18:30 (or somewhere near this time). Could that be it?

**Comment by shirubana** [comment]
This is part of what I'm mentioning that SAM/PVSyst and bifacial_radiance / bifacialvf calculate hte sun position different.

![image](https://user-images.githubusercontent.com/22824806/71494881-bed91000-2807-11ea-8615-6569dd3fe40c.png)

Still, that doesn't justify 15% difference. Have you tried running the same simulation without the torque tube? the torquetube creates shading that reduces rear irradiance.

Also, you seem to be doing this for tracking. Are you adding all of the values for the other angles too not just the center angle 0.0? Sum columns h of all the angles, and then take the average over the module.

Your collector width is also 2 m, for a ~1.4m clerance height. Are you keeping the same ratios for the module collector width and clerance height in PVsyst?

**Comment by costeladebarata** [comment]
So from your second picture do you think is fair to say that bifacial_radiance is "one hour ahead"?

Yes, I have created a script that calculates both, the idea was to estimate torque tube shading doing this comparison. But either way, at this point I'm worried that GII values are not matching PVsyst (or close enough), once this is sorted I imagine rear irradiation will come closer as well.

Yes, I'm taking all tracking angles. The thing is I've done similar calculations and comparisons with PVsyst for different sites and it was all fine. I had two cases where I had problems and in both I got the "sun altitude error".

Regarding PVsyst, the first step of my approach is to simulate the exact same conditions in both environments, which means no torque tube (or zero rear shadings) and zero transparency (or a very low value to account for thermal gap), with same dimensions (module dimensions, pitch, hub height, etc).

But back to the error message, if you said the issue should have been corrected in v0.3.4, do you have any clue about anything else that could be triggering the error message? I agree that sunset and sunrise shouldn't contribute that much to the annual irradiation but I can't think of anything else and the only difference to other successful simulations is this error message.

**Comment by shirubana** [comment]
I'll run some comparisons of my own ~ can you let me know at least one weather file you identifeid as working and one that didn't? Thank you!

**Comment by costeladebarata** [comment]
Hi Silvana, sorry for the late response, holidays..
See attached a zip file containing a pdf with characteristics and PVsyst/radiance comparison for three sites (one working and two not working, same error) and EPW files that I used.
Thank you so much for looking into this!
I've looked around, researched, ran many different simulations and can't find any solution for this, so any help is much appreciated!
Cheers

**Comment by shirubana** [comment]
Ok couple questions, observations while I proceed to test this myself:

Main doubts:
1) Your tracking limits vary throughout the information of inputs in PVSyst. Site 1 is either 52 or 72.1, site 2 is either 60 or 70.9, and site 3 is either 60 or 69.4. 
2) you are not considering torque tube but you are adding a  2% shading factor. If you can provide some more details on the torquetube (diamterer, distance to the module plane), I can implement that on bifacial_radiance and validate that number.
3) 

ther details
- I'm not sure what the near shadings is on site 1?
- Also not sure what is the GlobInc - 2.05% on site 1?
- I'm assuming the axis azimuth of -7 is this: 
![image](https://user-images.githubusercontent.com/22824806/71679809-b459d180-2d45-11ea-8493-760d12eea373.png)
Also note that this is southern hemisphere (I'm not sure if the standard is to orient the trackers slightly east for Northen Hemispheres and thus for southern hemisphere it would be to orient them slightly west?)

**Comment by shirubana** [comment]
Also on Site2 - what is "Tracker with torque tube gap"? What are you considering there?

**Comment by shirubana** [comment]
@costeladebarata can you send me an email to continue this by mail? silvana.ayala@nrel.gov  
I also have some files to share ~

One more thing. can you tell me how you're importing the EPW into pvsyst? I'm having issue with Cases 1 and 2 for the azimuth angle. 

Case 3 looks good:
![image](https://user-images.githubusercontent.com/22824806/71700198-6c0bd500-2d80-11ea-933d-15dd51effc24.png)

Case 2 and 1 not so muhc. I probably did something wrong, I have to go back and check:
![image](https://user-images.githubusercontent.com/22824806/71700223-80e86880-2d80-11ea-97a5-c67297f4f415.png)


![image](https://user-images.githubusercontent.com/22824806/71700229-880f7680-2d80-11ea-8334-d35a9dace08e.png)


This where my import notes:

CASE 1:

PVSYST V 6.84 - PRO30
Weather Files imported as Canada EPW (CWEC)
Site: Site1_Costal, Country Australia, Time Zone 10.0 
SaveSite: Site1_Costal_EPW    ((this creates the .SIT))
Weatherfile warning: The clearness index of the best  clear days seem high with respect to the clear day model.


CASE 2

PVSYST V 6.84 - PRO30
Weather Files imported as Canada EPW (CWEC)
Site: Site2_Costal, Country Tanzania, Time Zone 3 
This Meteo file seems to be OK
SaveSite: Site2_Costal_EPW    ((this creates the .SIT))

**Comment by costeladebarata** [comment]
Thanks Silvana, will reach out by email and post our findings here later.
